public class DLResult {
	@AuraEnabled
	public String firstName;
	@AuraEnabled
	public String lastName;
	@AuraEnabled
	public String streetAddress;
	@AuraEnabled
	public String cityAddress;
	@AuraEnabled
	public String stateAddress;
	@AuraEnabled
	public String zipCode;
	@AuraEnabled
	public Boolean isOrganDonor;
	@AuraEnabled
	public String dob;
	@AuraEnabled
	public String identifiedStateDL;
	@AuraEnabled
	public String contentVersionId;
}