global class IDResult {
	@AuraEnabled
	global String firstName;
	@AuraEnabled
	global String lastName;
	@AuraEnabled
	global String streetAddress;
	@AuraEnabled
	global String cityAddress;
	@AuraEnabled
	global String stateAddress;
	@AuraEnabled
	global String zipCode;
	@AuraEnabled
	global Boolean isOrganDonor;
	@AuraEnabled
	global String dob;
	@AuraEnabled
	global String identifiedStateDL;
	@AuraEnabled
	global String contentVersionId;
}